### ISSUE TITLE
[README] Need to Update

### ISSUE THREAD

**Issue by aminoxix** [amino19/covid19-tracker#3]
### What is your feature request related to?

- [x] Ideas
- [x] Designing
- [x] Documentation
- [x] Others [Styling, Adding some relevant badges, configure redirection images/links]

### Description:-
Add description, make it beautiful from your end, make use of references given below.

### Additional context
**Reference:**
- [150 badges](https://dev.to/envoy_/150-badges-for-github-pnk)
- [formica project readme.md](https://github.com/felixfaisal/formica/blob/main/README.md)

**Comment by artimanputra** [comment]
I would like to update the readme file, could you please assign it to me?

**Comment by aminoxix** [comment]
> I would like to update the readme file, could you please assign it to me?

Your stage, deffo! :100:

**Comment by aminoxix** [comment]
@artimanputra: Thanks for participating and contributing via #4! :sparkles:
